
modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="lvluping"
version="0.7"
displayName="LVLuping"

logoFile="logo.png"
authors="MrUtcka"

description='''
§6LLVuping§r — это расширенная система RPG-прогрессии, созданная для глубокого погружения в игровой процесс.

§eОсобенности системы:§r
• §bДинамическое развитие:§r Открывайте новые возможности персонажа по мере роста вашего мастерства.
• §aБоевое искусство:§r Каждое действие в бою теперь имеет значение. Используйте накопленный опыт, чтобы доминировать на поле битвы.
• §dГибкость и стиль:§r Выбирайте свой путь, комбинируя уникальные пассивные усиления и мощные активные приемы.

§7Станьте легендой этого мира, развивая свои таланты и адаптируясь к любым угрозам. Идеально сбалансировано для приключений и сложных сражений.§r
    '''

[[dependencies.lvluping]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"

[[dependencies.lvluping]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"